#!/bin/bash
set -e

source /opt/airquality/venv/bin/activate

set -a
source /opt/airquality/config/intelligence.env
set +a

cd /opt/airquality/github/SK_datapull

LOCKFILE="/opt/airquality/locks/sk_datapull_git.lock"
mkdir -p "$(dirname "$LOCKFILE")"

(
  flock -w 600 200

  git fetch origin
  git pull --rebase origin main

  # current_features.csv is regenerated by run_sk_site_update.sh (runs 10
  # min earlier, at :08/:38) - reusing it here instead of calling
  # build_current.py a second time halves our load on the province's
  # rate-limited ArcGIS endpoints for no loss of freshness.
  python web/SK_regina_blended_grid.py
  python scripts/build_eccc_forecasts.py

  git add data/sk_current_blend.geojson
  git add data/sk_forecast_3h_blend.geojson
  git add data/regina_current_blend.geojson
  git add data/regina_forecast_3h_blend.geojson
  git add data/station_forecast_3h_debug.csv
  git add data/aqhi_forecasts.geojson

  if git diff --cached --quiet; then
      echo "No changes to commit."
  else
      git commit -m "Update SK blended AQHI grids"
      for attempt in 1 2 3; do
          if git push origin main; then
              break
          fi
          echo "push rejected (attempt $attempt/3); rebasing onto latest and retrying..."
          git pull --rebase origin main
      done
  fi
) 200>"$LOCKFILE"
